spring:
  datasource:
    url: jdbc:postgresql://dpg-colrlgol5elc73bocuv0-a.oregon-postgres.render.com/coffee_hyxa
    username: coffee_hyxa_user
    password: iZSLfMYHcadmFjaZmDOyKJpAwV0Vu39i

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always